### ISSUE TITLE
Serious Issue-Payments not applying

### ISSUE THREAD

**Issue by mawdish** [kdflint/speedybooks-backlog#63]
Kathy I just noticed a serious issue that I never saw before beuase never tested it
when we pay the bil it isnt updating on the reports big problem please look into it , I actually paid a invoice for $15,000 in the mikemm48@yaoo.com account and it doesnt post to the reports , thanks

if you go to the dashbord you will see paid invoices it is $15,000 piad this shoud have hit the general ledger by debiting accounts paybales and crediting Cash thanks

**Comment by kdflint** [comment]
See #69 for solution
