### ISSUE TITLE
Expenses Issue 

### ISSUE THREAD

**Issue by mawdish** [kdflint/speedybooks-backlog#65]
Kathy quick update on the pamyents issue < this is very serious and critical I am sorry as i said many issues and by being able to test now I am finding this (edited)
when making a payment or receeving a payment the financials statements are not posting for example I have givven you screen shots

on github
so the following problem exsits for invvocies and expenses , when applying a payment for a bill in expesnes the cash account should be credited or reduced and accounts payables should be debited or reduced
also for invoices when receiving payments cash should be debited or increased and accounts recievables should be credite or reduced , fyi above when i told you about the $15000 invoice I should have told you debit Cash and credit Recceivables
I have placed this on git hub , very crucial we fix this thank you
![paid bill-3](https://user-images.githubusercontent.com/39473659/41207583-23a34e60-6cde-11e8-9824-6bf075f4a9a2.JPG)
![paid bill-2](https://user-images.githubusercontent.com/39473659/41207584-23b5acae-6cde-11e8-8dae-1f3ef3ea34a8.JPG)
![paid bill](https://user-images.githubusercontent.com/39473659/41207585-23c60914-6cde-11e8-9ec0-7b11afa1b758.JPG)

**Comment by kdflint** [comment]
Two problems spotted.

1. Queries from invoices and expenses table not bringing back paid_to and paid_from fields, respectively. Updates to api ReportController.js

2. One paid invoices did not have have "Cash Account" inserted into paid_to field. Why? How big is this impact> #69 opened for this.

**Comment by kdflint** [comment]
See #69 for solution
